### ISSUE TITLE
Dropdown value not changing

### ISSUE THREAD

**Issue by deep12650** [cetver/yii2-language-selector#1]
it is working fine and changing language but I did notice that the value in the drop-down is not changing until I did hard page refresh manually. Any Idea what should I do to resolve it. thanks

**Comment by cetver** [comment]
Probably `Yii::$app->language` is not set properly when you first visit the page. For example, the language is set from cookie: on first visit, a server sets the cookie (Set-Cookie header), but browser sends it only on next request (Cookie header)

**Comment by deep12650** [comment]
Thanks @cetver for your response, the problem has been solved.
