### ISSUE TITLE
Fails with en-US

### ISSUE THREAD

**Issue by Eseperio** [cetver/yii2-language-selector#3]
DropDownLanguageItem throws an exception when a language is partially supported. I.e; `en-US` is `en`, but fails because not checking only first two characters

**Comment by cetver** [comment]
You use mix with the localization and the internationalization - this is incorrect.

localization - different entities (number format, money format, etc) must be supported and shown to the user
- en_US
- en_GB
- en_OTHER_LOCALE

internationalization - only translation without country specificities  (number format, money format, etc)
- en

**Comment by Eseperio** [comment]
`Yii::$app->language` returns `en-US`, as you can configure it in chrome. Also english from US is not the same as in UK, and spanish is quite different in spain than in mexico, so country is not only for currency or number formatting.

**Comment by cetver** [comment]
You use localization, so `languages` must look like
```
'en_US' => 'American English',
'en_GB' => 'British English',
```
Without internationalization `en` key

**Comment by Eseperio** [comment]
The problem is that this library is asking for Yii::$app->language, which triggers an exception on browsers configured as en-US and similar.
https://github.com/cetver/yii2-language-selector/blob/370fd07d62c057b227f2819103499ccb890dbcc2/items/DropDownLanguageItem.php#L79

**Comment by cetver** [comment]
This package has nothing to do with browser languages.
It handles only mapped languages:
```php
new cetver\LanguageSelector\items\MenuLanguageItems([
    // the list of available languages
    'languages' => [
        'en-US' => 'American English',
    ],
    /*
    or
    'languages' => function () {
       return \app\models\Language::find()
                    ->select(['code', 'name'])
                    ->createCommand()
                    ->queryAll(\PDO::FETCH_KEY_PAIR);
    }
    */
]);
```
If your app set all languages or locale languages (en, en_US, en-US) - it is invalid behavior. You need to convert the value of the  `Yii::$app->language` in one format: 
en -> en-US
en_US -> en-US
